# File: codecov.yml
# Description: Code coverage configuration for Codecov.
# Author: Noé Henchoz
# License: MIT
# Copyright (c) 2026 Noé Henchoz

codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
