/**
 * File: src/managers/cleaner.ts
 * Description: Removes all GitSetup-generated configurations and keys
 * Author: Noé Henchoz
 * License: MIT
 * Copyright (c) 2026 Noé Henchoz
 */

import { rm, unlink } from 'node:fs/promises'
import { join } from 'node:path'
import {
  GIT_TEMPLATE_DIR,
  GITCONFIG_DEST,
  GITIGNORE_DEST,
  SSH_KEY_TYPE,
  SSH_MARKER_END,
  SSH_MARKER_START,
} from '../core/constants.ts'
import type { AppConfig, AppOptions } from '../core/types.ts'
import { updateFileBlock } from '../utils/file-block.ts'
import { homePath, pathExists } from '../utils/file-ops.ts'
import { logInfo, logSuccess, logWarning } from '../utils/logger.ts'
import { confirmAction } from '../utils/prompt.ts'
import { sanitizeHost } from '../utils/sanitize.ts'

/** Removes all configurations, keys, and hooks generated by GitSetup. */
export async function runCleaner(
  config: AppConfig,
  options: AppOptions,
): Promise<void> {
  logWarning(
    '!!! WARNING: This will remove all GitSetup-generated configurations !!!',
  )

  const confirmed = await confirmAction(
    'Are you sure you want to clean all GitSetup configurations?',
    options.assumeYes,
  )

  if (!confirmed) {
    logInfo('Cleanup cancelled')
    return
  }

  await removeFileIfExists(homePath(GITCONFIG_DEST), options.dryRun)
  await removeFileIfExists(homePath(GITIGNORE_DEST), options.dryRun)

  const templateDir = homePath(GIT_TEMPLATE_DIR)
  if (await pathExists(templateDir)) {
    if (options.dryRun) {
      logInfo(`[DRY-RUN] Would remove directory ${templateDir}`)
    } else {
      await rm(templateDir, { recursive: true })
      logInfo(`Removed ${templateDir}`)
    }
  }

  const sshConfigPath = join(options.sshDir, 'config')
  await updateFileBlock(
    sshConfigPath,
    SSH_MARKER_START,
    SSH_MARKER_END,
    '',
    options.dryRun,
  )
  logInfo('Removed GitSetup block from SSH config')

  for (const profile of config.profiles) {
    const keyName = `id_${SSH_KEY_TYPE}_${sanitizeHost(profile.host)}`
    const keyPath = join(options.sshDir, keyName)
    await removeFileIfExists(keyPath, options.dryRun)
    await removeFileIfExists(`${keyPath}.pub`, options.dryRun)
  }

  logSuccess('Cleanup complete')
}

/** Removes a file if it exists, respecting dry-run mode. */
async function removeFileIfExists(
  filePath: string,
  dryRun: boolean,
): Promise<void> {
  const exists = await pathExists(filePath)
  if (!exists) return

  if (dryRun) {
    logInfo(`[DRY-RUN] Would remove ${filePath}`)
    return
  }

  await unlink(filePath)
  logInfo(`Removed ${filePath}`)
}
