#!/bin/bash
# ==============================================================================
# File:        lib/cleaner.sh
# Description: Removes files and configurations generated by GitSetup.
# Author:      Noé Henchoz <henchoznoe@gmail.com>
# Date:        2025-12-21
# License:     MIT
# ==============================================================================

# Internal callback for cleaning up keys
# Context: Expects SSH_DIR to be defined (exported from main)
_cleaner_process_profile() {
    local host="$1"
    local email="$2"

    local host_slug
    host_slug=$(utils_sanitize_host "$host")
    local key_name="id_ed25519_${host_slug}"
    
    # Remove private and public keys
    utils_execute "Removing key: $key_name" rm -f "$SSH_DIR/$key_name"
    utils_execute "Removing pub key: $key_name.pub" rm -f "$SSH_DIR/$key_name.pub"
}

cleaner_run() {
    log_warning "!!! WARNING !!!"
    log_warning "You are about to remove all GitSetup configurations."
    
    if [[ "${GITSETUP_DRY_RUN}" != "true" ]]; then
        read -p "Are you sure? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_error "Cleanup aborted." 1
        fi
    fi

    log_info "--- Starting Cleanup ---"

    # 1. Global Configs
    utils_execute "Removing .gitconfig" rm -f "$HOME/.gitconfig"
    utils_execute "Removing .gitignore_global" rm -f "$HOME/.gitignore_global"
    utils_execute "Removing .git_template" rm -rf "$HOME/.git_template"
    utils_execute "Removing SSH config" rm -f "$SSH_DIR/config"

    # 2. Dynamic SSH Keys Removal
    config_for_each_profile _cleaner_process_profile

    log_success "Cleanup complete."
}
