#!/bin/bash
# ==============================================================================
# File:        lib/cleaner.sh
# Description: Removes files and configurations generated by GitSetup.
# Author:      Noé Henchoz <henchoznoe@gmail.com>
# Date:        2025-12-21
# License:     MIT
# ==============================================================================

# Helper to match the one in ssh_manager
_cleaner_sanitize_host() {
    echo "$1" | tr '.' '_'
}

cleaner_run() {
    log_warning "!!! WARNING !!!"
    log_warning "You are about to remove all GitSetup configurations."
    
    if [[ "${GITSETUP_DRY_RUN}" != "true" ]]; then
        read -p "Are you sure? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_error "Cleanup aborted." 1
        fi
    fi

    log_info "--- Starting Cleanup ---"

    # 1. Global Configs
    utils_execute "rm -f \"$HOME/.gitconfig\"" "Removing .gitconfig"
    utils_execute "rm -f \"$HOME/.gitignore_global\"" "Removing .gitignore_global"
    utils_execute "rm -rf \"$HOME/.git_template\"" "Removing .git_template"
    utils_execute "rm -f \"$SSH_DIR/config\"" "Removing SSH config"

    # 2. Dynamic SSH Keys Removal
    IFS=',' read -ra PROFILES <<< "$GIT_PROFILES"
    
    for profile in "${PROFILES[@]}"; do
        IFS=':' read -r host email <<< "$profile"
        host=$(echo "$host" | xargs)
        
        if [[ -n "$host" ]]; then
            local host_slug
            host_slug=$(_cleaner_sanitize_host "$host")
            local key_name="id_ed25519_${host_slug}"
            
            # Remove private and public keys
            utils_execute "rm -f \"$SSH_DIR/$key_name\"" "Removing key: $key_name"
            utils_execute "rm -f \"$SSH_DIR/$key_name.pub\"" "Removing pub key: $key_name.pub"
        fi
    done

    log_success "Cleanup complete."
}
