#!/bin/bash
# ==============================================================================
# File:        lib/git_manager.sh
# Description: Manages global Git configuration, ignore files, and hooks.
# Author:      Noé Henchoz <henchoznoe@gmail.com>
# Date:        2025-12-21
# License:     MIT
# ==============================================================================

# Function: git_configure_global
# Description: Applies the global .gitconfig from template.
# Arguments:
#   $1 - Template path
git_configure_global() {
    local template="$1"
    local destination="$HOME/.gitconfig"

    log_info "Configuring global .gitconfig..."
    
    if [[ ! -f "$template" ]]; then
        log_error "Git config template missing: $template" 1
    fi

    utils_backup_file "$destination"

    # Restrict envsubst to specific variables to avoid accidental replacements
    # (though less risky in .gitconfig than in hooks)
    export GIT_USER_NAME GIT_USER_EMAIL_DEFAULT GIT_CORE_EDITOR
    envsubst < "$template" > "$destination"

    log_success "Global Git config updated."
}

# Function: git_configure_ignore
# Description: Applies the global .gitignore from template.
# Arguments:
#   $1 - Template path
git_configure_ignore() {
    local template="$1"
    local destination="$HOME/.gitignore_global"

    log_info "Configuring global .gitignore..."
    utils_backup_file "$destination"
    cp "$template" "$destination"
    log_success "Global .gitignore updated."
}

# Internal callback for processing hook rules
# Context: Expects $hook_script to be defined
_git_process_hook_profile() {
    local host="$1"
    local email="$2"

    log_info "-> Adding rule: $host => $email"
    
    # Append the case logic to the file
    cat >> "$hook_script" <<ENTRY
  *"$host"*)
    git config user.email "$email"
    echo "🔄 [Hook] Detected: $host. Email set to $email"
    ;;
ENTRY
}

# Function: git_install_hooks
# Description: Generates and installs a dynamic email-switching hook based on GIT_PROFILES.
# Arguments: None (uses global GIT_PROFILES variable)
git_install_hooks() {
    local template_dir="$HOME/.git_template/hooks"
    local hook_script="$template_dir/post-checkout"

    log_info "Generating dynamic Git hooks..."

    utils_execute "Creating hook directory" mkdir -p "$template_dir"

    # Start writing the hook script (Shebang + Preamble)
    cat > "$hook_script" <<EOF
#!/bin/bash
# Hook generated by GitSetup
# Automatically adjust Git user email based on the remote host

remote_url=\$(git remote get-url origin 2>/dev/null)
if [ -z "\$remote_url" ]; then exit 0; fi

# Clean the remote URL to match simpler host strings
# (This helps matching logic inside the case statement)
case "\$remote_url" in
    *"@"*) host_part=\$(echo "\$remote_url" | cut -d@ -f2 | cut -d: -f1) ;;
    *"//"*) host_part=\$(echo "\$remote_url" | cut -d/ -f3) ;;
    *) host_part="\$remote_url" ;;
esac

case "\$host_part" in
EOF

    # ---------------------------------------------------------
    # DYNAMIC GENERATION LOOP
    # ---------------------------------------------------------
    config_for_each_profile _git_process_hook_profile

    # ---------------------------------------------------------
    # CLOSE THE SCRIPT
    # ---------------------------------------------------------
    cat >> "$hook_script" <<EOF
  *)
    git config user.email "$GIT_USER_EMAIL_DEFAULT"
    echo "🔄 [Hook] Unknown host. Email reset to default ($GIT_USER_EMAIL_DEFAULT)"
    ;;
esac
EOF

    # Make it executable and copy to other hooks
    utils_execute "Making hook executable" chmod +x "$hook_script"

    local hooks=("post-commit" "post-merge" "post-pull")
    for h in "${hooks[@]}"; do
        utils_execute "Copying hook to $h" cp "$hook_script" "$template_dir/$h"
    done

    # ---------------------------------------------------------
    # OPTIONAL: CONVENTIONAL COMMITS HOOK (commit-msg)
    # ---------------------------------------------------------
    if [[ "${ENABLE_CONVENTIONAL_COMMITS}" == "true" ]]; then
        local commit_hook_dest="$template_dir/commit-msg"

        log_info "Installing Conventional Commits hook..."

        cat > "$commit_hook_dest" <<EOF
#!/bin/bash
# Hook generated by GitSetup
# Enforces Conventional Commits specification

commit_msg_file="\$1"
commit_msg=\$(cat "\$commit_msg_file")

# Regex for Conventional Commits
# Format: type(scope): subject
types="(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)"
regex="^\$types(\(.+\))?: .+\$"

if ! echo "\$commit_msg" | grep -qE "\$regex"; then
    echo "❌ [Commit Hook] Invalid commit message format."
    echo "   Expected: <type>(<scope>): <subject>"
    echo "   Example:  feat(auth): add login support"
    echo "   Types:    feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
    echo
    exit 1
fi
EOF
        
        utils_execute "Making commit-msg executable" chmod +x "$commit_hook_dest"
    fi

    # Configure Git to use this template
    utils_execute "Setting init.templatedir" git config --global init.templatedir "$HOME/.git_template"

    log_success "Dynamic Git hooks installed."
}
