#!/bin/bash
# ==============================================================================
# File:        lib/git_manager.sh
# Description: Manages global Git configuration, ignore files, and hooks.
# Author:      Noé Henchoz <henchoznoe@gmail.com>
# Date:        2025-12-21
# License:     MIT
# ==============================================================================

# Function: git_configure_global
# Description: Applies the global .gitconfig from template.
# Arguments:
#   $1 - Template path
# Function: git_configure_global
# Description: Applies the global .gitconfig from template.
# Arguments:
#   $1 - Template path
git_configure_global() {
    local template="$1"
    local destination="$HOME/.gitconfig"

    log_info "Configuring global .gitconfig..."
    
    if [[ ! -f "$template" ]]; then
        log_error "Git config template missing: $template" 1
    fi

    if [[ -f "$destination" ]]; then
        if ! utils_confirm "Overwrite existing $destination?"; then
            log_warning "Skipping global gitconfig update."
            return 0
        fi
        utils_backup_file "$destination"
    fi

    # Restrict envsubst to specific variables with sanitized inputs
    export GIT_USER_NAME GIT_USER_EMAIL_DEFAULT GIT_CORE_EDITOR
    
    if [[ "${GITSETUP_DRY_RUN}" != "true" ]]; then
        envsubst < "$template" > "$destination"
    else
        log_warning "[DRY-RUN] Would generate $destination from $template"
    fi

    log_success "Global Git config updated."
}

# Function: git_configure_ignore
# Description: Applies the global .gitignore from template.
# Arguments:
#   $1 - Template path
git_configure_ignore() {
    local template="$1"
    local destination="$HOME/.gitignore_global"

    log_info "Configuring global .gitignore..."
    
    if [[ -f "$destination" ]]; then
        if ! utils_confirm "Overwrite existing $destination?"; then
             log_warning "Skipping global gitignore update."
             return 0
        fi
        utils_backup_file "$destination"
    fi
    
    utils_execute "Installing global .gitignore" cp "$template" "$destination"
    log_success "Global .gitignore updated."
}

# Internal callback for processing hook rules
# Context: Expects $hook_script to be defined
_git_process_hook_profile() {
    local host="$1"
    local email="$2"

    log_info "-> Adding rule: $host => $email"
    
    # Append the case logic to the file
    cat >> "$hook_script" <<ENTRY
  *"$host"*)
    git config user.email "$email"
    echo "🔄 [Hook] Switched to: $host ($email)"
    ;;
ENTRY
}

# Function: git_install_hooks
# Description: Generates and installs a dynamic email-switching hook based on GIT_PROFILES.
# Arguments: None (uses global GIT_PROFILES variable)
git_install_hooks() {
    local template_dir="$HOME/.git_template/hooks"
    local hook_script="$template_dir/post-checkout"

    log_info "Generating dynamic Git hooks..."

    utils_execute "Creating hook directory" mkdir -p "$template_dir"

    # Check for existing hook
    if [[ -f "$hook_script" ]]; then
        # Check if it was generated by us (simple grep)
        if ! grep -q "GitSetup" "$hook_script"; then
            if ! utils_confirm "A post-checkout hook already exists and was not created by GitSetup. Overwrite?"; then
                log_warning "Skipping post-checkout hook installation."
                return 0
            fi
        fi
    fi

    # Start writing the hook script (Shebang + Preamble)
    if [[ "${GITSETUP_DRY_RUN}" != "true" ]]; then
        cat > "$hook_script" <<EOF
#!/bin/bash
# Hook generated by GitSetup
# Automatically adjust Git user email based on the remote host

remote_url=\$(git remote get-url origin 2>/dev/null)
if [ -z "\$remote_url" ]; then exit 0; fi

# Clean the remote URL to match simpler host strings
# (This helps matching logic inside the case statement)
case "\$remote_url" in
    *"@"*) host_part=\$(echo "\$remote_url" | cut -d@ -f2 | cut -d: -f1) ;;
    *"//"*) host_part=\$(echo "\$remote_url" | cut -d/ -f3) ;;
    *) host_part="\$remote_url" ;;
esac

case "\$host_part" in
EOF

    # ---------------------------------------------------------
    # DYNAMIC GENERATION LOOP
    # ---------------------------------------------------------
    config_for_each_profile _git_process_hook_profile

    # ---------------------------------------------------------
    # CLOSE THE SCRIPT
    # ---------------------------------------------------------
    cat >> "$hook_script" <<EOF
  *)
    git config user.email "$GIT_USER_EMAIL_DEFAULT"
    echo "🔄 [Hook] Unknown host. Switched to default ($GIT_USER_EMAIL_DEFAULT)"
    ;;
esac
EOF
    fi
    
    local tmp_hook
    tmp_hook=$(mktemp)
    
    cat > "$tmp_hook" <<EOF
#!/bin/bash
# Hook generated by GitSetup
# Automatically adjust Git user email based on the remote host

remote_url=\$(git remote get-url origin 2>/dev/null)
if [ -z "\$remote_url" ]; then exit 0; fi

case "\$remote_url" in
    *"@"*) host_part=\$(echo "\$remote_url" | cut -d@ -f2 | cut -d: -f1) ;;
    *"//"*) host_part=\$(echo "\$remote_url" | cut -d/ -f3) ;;
    *) host_part="\$remote_url" ;;
esac

case "\$host_part" in
EOF

    local real_hook_script="$hook_script"
    hook_script="$tmp_hook"
    
    config_for_each_profile _git_process_hook_profile
    
    cat >> "$tmp_hook" <<EOF
  *)
    git config user.email "$GIT_USER_EMAIL_DEFAULT"
    echo "🔄 [Hook] Unknown host. Switched to default ($GIT_USER_EMAIL_DEFAULT)"
    ;;
esac
EOF

    # Restore variable
    hook_script="$real_hook_script"

    # Install the hook
    utils_execute "Installing hook script" mv "$tmp_hook" "$hook_script"
    utils_execute "Making hook executable" chmod +x "$hook_script"

    local hooks=("post-commit" "post-merge" "post-pull")
    for h in "${hooks[@]}"; do
        utils_execute "Copying hook to $h" cp "$hook_script" "$template_dir/$h"
    done

    # ---------------------------------------------------------
    # OPTIONAL: CONVENTIONAL COMMITS HOOK (commit-msg)
    # ---------------------------------------------------------
    if [[ "${ENABLE_CONVENTIONAL_COMMITS}" == "true" ]]; then
        local commit_hook_dest="$template_dir/commit-msg"

        log_info "Installing Conventional Commits hook..."
        
        if [[ -f "$commit_hook_dest" ]]; then
             if ! grep -q "GitSetup" "$commit_hook_dest"; then
                 if ! utils_confirm "Overwrite existing commit-msg hook?"; then
                     log_warning "Skipping commit-msg hook."
                 else
                     _git_install_commit_msg_hook "$commit_hook_dest"
                 fi
             else
                 _git_install_commit_msg_hook "$commit_hook_dest"
             fi
        else
             _git_install_commit_msg_hook "$commit_hook_dest"
        fi
    fi

    # Configure Git to use this template
    utils_execute "Setting init.templatedir" git config --global init.templatedir "$HOME/.git_template"

    log_success "Dynamic Git hooks installed."
}

_git_install_commit_msg_hook() {
    local dest="$1"
    local tmp_msg
    tmp_msg=$(mktemp)
    
    cat > "$tmp_msg" <<EOF
#!/bin/bash
# Hook generated by GitSetup
# Enforces Conventional Commits specification

commit_msg_file="\$1"
commit_msg=\$(cat "\$commit_msg_file")

# Regex for Conventional Commits
# Format: type(scope): subject
types="(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)"
regex="^\$types(\(.+\))?: .+\$"

if ! echo "\$commit_msg" | grep -qE "\$regex"; then
    echo "❌ [Commit Hook] Invalid commit message format."
    echo "   Expected: <type>(<scope>): <subject>"
    echo "   Example:  feat(auth): add login support"
    echo "   Types:    feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
    echo
    exit 1
fi
EOF
    utils_execute "Installing commit-msg hook" mv "$tmp_msg" "$dest"
    utils_execute "Making commit-msg executable" chmod +x "$dest"
}
