#!/bin/bash
# ==============================================================================
# File:        lib/ssh_manager.sh
# Description: Manages SSH keys and config dynamically based on GIT_PROFILES.
# Author:      Noé Henchoz <henchoznoe@gmail.com>
# Date:        2025-12-21
# License:     MIT
# ==============================================================================

# Helper: sanitize host for filename (e.g., github.com -> github_com)
_ssh_sanitize_host() {
    echo "$1" | tr '.' '_'
}

# Function: ssh_setup_dynamic
# Description: Generates keys and writes the SSH config file loop-style.
ssh_setup_dynamic() {
    local ssh_dir="$1"
    local config_file="$ssh_dir/config"
    
    # Ensure directory exists
    if [[ ! -d "$ssh_dir" ]]; then
        utils_execute "mkdir -p \"$ssh_dir\"" "Creating SSH directory"
        utils_execute "chmod 700 \"$ssh_dir\"" "Securing SSH directory"
    fi

    # Backup existing config
    utils_backup_file "$config_file"

    log_info "Generating SSH configuration..."

    # Start writing the config file header
    if [[ "${GITSETUP_DRY_RUN}" != "true" ]]; then
        cat > "$config_file" <<EOF
# ==============================================================================
# SSH Config generated by GitSetup
# ==============================================================================
EOF
    fi

    # Loop through profiles
    IFS=',' read -ra PROFILES <<< "$GIT_PROFILES"
    
    for profile in "${PROFILES[@]}"; do
        IFS=':' read -r host email <<< "$profile"
        host=$(echo "$host" | xargs)
        email=$(echo "$email" | xargs)

        if [[ -n "$host" && -n "$email" ]]; then
            # Define consistent key filename: id_ed25519_github_com
            local host_slug
            host_slug=$(_ssh_sanitize_host "$host")
            local key_name="id_ed25519_${host_slug}"
            local key_path="$ssh_dir/$key_name"

            # 1. Generate Key if missing
            if [[ ! -f "$key_path" ]]; then
                log_info "Generating key for $host ($email)..."
                local cmd="ssh-keygen -t ed25519 -C \"$email\" -f \"$key_path\" -N \"\" >/dev/null 2>&1"
                utils_execute "$cmd" "Generating SSH key: $key_name"
            else
                log_info "Key exists for $host: $key_name"
            fi

            # 2. Append block to SSH Config
            log_info "-> Adding config block for $host"
            
            if [[ "${GITSETUP_DRY_RUN}" != "true" ]]; then
                cat >> "$config_file" <<EOF

# --- $host ---
Host $host
    HostName $host
    User git
    IdentityFile $key_path
    IdentitiesOnly yes
EOF
            else
                log_warning "[DRY-RUN] Would append config block for $host pointing to $key_path"
            fi
        fi
    done

    # Secure the config file
    utils_execute "chmod 600 \"$config_file\"" "Securing SSH config file"
    log_success "SSH setup complete."
}
