/**
 * File: src/core/constants.ts
 * Description: Named constants used across the application
 * Author: Noé Henchoz
 * License: MIT
 * Copyright (c) 2026 Noé Henchoz
 */

/** Marker lines for non-destructive SSH config editing. */
export const SSH_MARKER_START =
  '# ==================== GITSETUP START ===================='
export const SSH_MARKER_END =
  '# ==================== GITSETUP END ===================='

/** SSH key algorithm used for all generated keys. */
export const SSH_KEY_TYPE = 'ed25519'

/** File permission for ~/.ssh directory. */
export const SSH_DIR_PERMISSIONS = 0o700

/** File permission for SSH config and private keys. */
export const SSH_FILE_PERMISSIONS = 0o600

/** Signature embedded in generated hook scripts. */
export const HOOK_SIGNATURE = 'Hook generated by GitSetup'

/** Regex pattern for Conventional Commits validation. */
export const CONVENTIONAL_COMMIT_REGEX =
  /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .+$/

/** Git global config keys set by GPG signing configuration. */
export const GPG_GIT_CONFIG_KEYS = [
  'user.signingkey',
  'gpg.program',
  'commit.gpgsign',
  'tag.gpgsign',
] as const

/** Git global config key for template directory. */
export const TEMPLATE_DIR_GIT_CONFIG_KEY = 'init.templatedir'

/** Git template directory name relative to HOME. */
export const GIT_TEMPLATE_DIR = '.git_template'

/** Default gitconfig destination relative to HOME. */
export const GITCONFIG_DEST = '.gitconfig'

/** Default global gitignore destination relative to HOME. */
export const GITIGNORE_DEST = '.gitignore_global'

/** Hooks directory relative to the git template directory. */
export const HOOKS_DIR = 'hooks'

/** Config directory relative to HOME (XDG-compliant). */
export const CONFIG_DIR = '.config/git-setup'

/** Config filename for JSON-based configuration. */
export const CONFIG_FILE = 'config.json'

/** Git aliases installed by GitSetup with their descriptions. */
export const GIT_ALIASES: readonly {
  alias: string
  command: string
  description: string
}[] = [
  { alias: 'a', command: 'add .', description: 'Stage all changes' },
  { alias: 's', command: 'status', description: 'Show working tree status' },
  { alias: 'br', command: 'branch', description: 'List or manage branches' },
  {
    alias: 'co',
    command: 'checkout',
    description: 'Switch branches or restore files',
  },
  {
    alias: 'com',
    command: 'checkout main',
    description: 'Switch to main branch',
  },
  {
    alias: 'cod',
    command: 'checkout develop',
    description: 'Switch to develop branch',
  },
  { alias: 'ci', command: 'commit', description: 'Create a commit' },
  {
    alias: 'cm',
    command: 'commit -m',
    description: 'Create a commit with message',
  },
  {
    alias: 'ca',
    command: 'commit --amend',
    description: 'Amend the last commit',
  },
  {
    alias: 'can',
    command: 'commit --amend --no-edit',
    description: 'Amend without editing message',
  },
  {
    alias: 'cp',
    command: 'cherry-pick',
    description: 'Apply a commit from another branch',
  },
  { alias: 'd', command: 'diff', description: 'Show unstaged changes' },
  { alias: 'ds', command: 'diff --staged', description: 'Show staged changes' },
  {
    alias: 'f',
    command: 'fetch --all --prune',
    description: 'Fetch all remotes and prune',
  },
  {
    alias: 'l',
    command: 'log --oneline --graph --decorate -20',
    description: 'Compact log (last 20)',
  },
  {
    alias: 'la',
    command: 'log --oneline --graph --decorate --all',
    description: 'Full graph log',
  },
  { alias: 'p', command: 'pull', description: 'Pull with rebase' },
  { alias: 'ps', command: 'push', description: 'Push current branch' },
  {
    alias: 'pf',
    command: 'push --force-with-lease',
    description: 'Force push (safe)',
  },
  { alias: 'rb', command: 'rebase', description: 'Rebase current branch' },
  { alias: 'rbi', command: 'rebase -i', description: 'Interactive rebase' },
  { alias: 'rs', command: 'restore --staged', description: 'Unstage files' },
  { alias: 'st', command: 'stash', description: 'Stash changes' },
  { alias: 'stp', command: 'stash pop', description: 'Pop last stash' },
  { alias: 'sw', command: 'switch', description: 'Switch to a branch' },
  {
    alias: 'swc',
    command: 'switch -c',
    description: 'Create and switch to new branch',
  },
  {
    alias: 'undo',
    command: 'reset HEAD~1 --mixed',
    description: 'Undo last commit (keep changes)',
  },
]

/** Resolves final alias list by merging defaults with user overrides. */
export function resolveAliases(
  overrides: readonly { alias: string; command?: string; disabled?: boolean }[],
): { alias: string; command: string; description: string }[] {
  const result = GIT_ALIASES.map(def => ({ ...def }))

  for (const override of overrides) {
    const idx = result.findIndex(a => a.alias === override.alias)

    if (idx !== -1) {
      if (override.disabled) {
        result.splice(idx, 1)
      } else if (override.command) {
        result[idx] = {
          ...result[idx],
          command: override.command,
          description: 'custom',
        }
      }
    } else if (override.command && !override.disabled) {
      result.push({
        alias: override.alias,
        command: override.command,
        description: 'custom',
      })
    }
  }

  return result
}
