/**
 * File: src/core/constants.ts
 * Description: Named constants used across the application
 * Author: Noé Henchoz
 * License: MIT
 * Copyright (c) 2026 Noé Henchoz
 */

/** Marker lines for non-destructive SSH config editing. */
export const SSH_MARKER_START =
  '# ==================== GITSETUP START ===================='
export const SSH_MARKER_END =
  '# ==================== GITSETUP END ===================='

/** SSH key algorithm used for all generated keys. */
export const SSH_KEY_TYPE = 'ed25519'

/** File permission for ~/.ssh directory. */
export const SSH_DIR_PERMISSIONS = 0o700

/** File permission for SSH config and private keys. */
export const SSH_FILE_PERMISSIONS = 0o600

/** Signature embedded in generated hook scripts. */
export const HOOK_SIGNATURE = 'Hook generated by GitSetup'

/** Regex pattern for Conventional Commits validation. */
export const CONVENTIONAL_COMMIT_REGEX =
  /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .+$/

/** Git template directory name relative to HOME. */
export const GIT_TEMPLATE_DIR = '.git_template'

/** Default gitconfig destination relative to HOME. */
export const GITCONFIG_DEST = '.gitconfig'

/** Default global gitignore destination relative to HOME. */
export const GITIGNORE_DEST = '.gitignore_global'

/** Hooks directory relative to the git template directory. */
export const HOOKS_DIR = 'hooks'

/** Config directory relative to HOME (XDG-compliant). */
export const CONFIG_DIR = '.config/git-setup'

/** Config filename for JSON-based configuration. */
export const CONFIG_FILE = 'config.json'

/** Legacy .env filename (for migration detection). */
export const LEGACY_ENV_FILE = '.env'
