name: CI

on:
  workflow_call:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: Run tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: brew install gettext gnupg

    - name: Run Functional Tests
      run: ./tests/test_setup.sh
