name: CI

on:
  workflow_call:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gettext-base

    - name: Run Functional Tests
      run: ./tests/test_setup.sh
